version: '3.8'

services:
  spinwheel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-$(date +%s)}  # Uses current timestamp as cache buster
    ports:
      - "3000:3000"
    volumes:
      - ./my-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
